name: Test Action

on:
  pull_request:
    branches: ['main']

jobs:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: 'Install Node'
    uses: actions/setup-node@v2
    with:
      node-version: '16.x'
  - name: Run this actions
    uses: ./
